# Generated by Django 2.1.5 on 2019-02-20 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190220_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.png', height_field=200, max_length=500, upload_to='student_pics/', width_field=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
