# Generated by Django 2.1.5 on 2019-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190220_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[(1, 'sem 1'), (2, 'sem 2'), (3, 'sem 3'), (4, 'sem 4'), (5, 'sem 5'), (6, 'sem 6'), (7, 'sem 7'), (8, 'sem 8'), (9, 'sem 9'), (10, 'sem 10')], default='Select Sem', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.png', max_length=500, upload_to='student_pics/'),
        ),
    ]
