# Generated by Django 2.1.5 on 2019-02-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190220_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='/media/student_pics/default.png', max_length=500, upload_to='student_pics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[('sem 1', 'sem 1'), ('sem 2', 'sem 2'), ('sem 3', 'sem 3'), ('sem 4', 'sem 4'), ('sem 5', 'sem 5'), ('sem 6', 'sem 6'), ('sem 7', 'sem 7'), ('sem 8', 'sem 8'), ('sem 9', 'sem 9'), ('sem 10', 'sem 10')], default='Select Sem', max_length=10),
        ),
    ]
