# Generated by Django 2.1.7 on 2019-02-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190221_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='student_pics/default.png', max_length=500, upload_to='student_pics/'),
        ),
    ]
