# Generated by Django 2.1.7 on 2019-02-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20190222_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default='Select Course', on_delete=django.db.models.deletion.PROTECT, to='data.Course'),
        ),
    ]
