# Generated by Django 2.1.7 on 2019-02-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20190222_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='data.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[('semester 1', 'Semester 1'), ('semester 2', 'Semester 2'), ('semester 3', 'Semester 3'), ('semester 4', 'Semester 4'), ('semester 5', 'Semester 5'), ('semester 6', 'Semester 6'), ('semester 7', 'Semester 7'), ('semester 8', 'Semester 8'), ('semester 9', 'Semester 9'), ('semester 10', 'Semester 10')], max_length=12),
        ),
    ]
