# Generated by Django 2.1.7 on 2019-02-23 12:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0015_auto_20190222_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sem', models.CharField(choices=[('semester 1', 'Semester 1'), ('semester 2', 'Semester 2'), ('semester 3', 'Semester 3'), ('semester 4', 'Semester 4'), ('semester 5', 'Semester 5'), ('semester 6', 'Semester 6'), ('semester 7', 'Semester 7'), ('semester 8', 'Semester 8'), ('semester 9', 'Semester 9'), ('semester 10', 'Semester 10')], max_length=12)),
                ('course', models.ManyToManyField(to='data.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Course'),
        ),
    ]
