# Generated by Django 2.1.7 on 2019-02-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20190223_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Course')),
                ('lecture_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Schedule')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Student')),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Subject')),
            ],
        ),
    ]
