# Generated by Django 2.1.7 on 2019-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_attendance_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mark',
            field=models.BooleanField(default=True),
        ),
    ]
