# Generated by Django 2.1.7 on 2019-02-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_attendance_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
