# Generated by Django 2.1.7 on 2019-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20190226_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
    ]
