# Generated by Django 2.1.7 on 2019-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20190226_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=250, unique=True, verbose_name='subject name'),
        ),
    ]
