# Generated by Django 2.1.7 on 2019-02-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20190227_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(default='Subject Deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='data.Subject'),
        ),
    ]
