# Generated by Django 2.1.7 on 2019-02-28 15:56

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_date', models.DateField(default=datetime.date.today)),
                ('mark', models.BooleanField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sem', models.CharField(choices=[('semester 1', 'Semester 1'), ('semester 2', 'Semester 2'), ('semester 3', 'Semester 3'), ('semester 4', 'Semester 4'), ('semester 5', 'Semester 5'), ('semester 6', 'Semester 6'), ('semester 7', 'Semester 7'), ('semester 8', 'Semester 8'), ('semester 9', 'Semester 9'), ('semester 10', 'Semester 10')], max_length=12)),
                ('day', models.CharField(default=None, max_length=42)),
                ('course', models.ManyToManyField(to='course.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.Subject'),
        ),
    ]
