# Generated by Django 2.1.7 on 2019-02-28 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=250)),
                ('sem', models.CharField(choices=[('semester 1', 'Semester 1'), ('semester 2', 'Semester 2'), ('semester 3', 'Semester 3'), ('semester 4', 'Semester 4'), ('semester 5', 'Semester 5'), ('semester 6', 'Semester 6'), ('semester 7', 'Semester 7'), ('semester 8', 'Semester 8'), ('semester 9', 'Semester 9'), ('semester 10', 'Semester 10')], max_length=12)),
                ('image', models.ImageField(default='student_pics/default.png', max_length=500, upload_to='student_pics/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course')),
                ('subject', models.ManyToManyField(to='subject.Subject')),
            ],
        ),
    ]
